---
network: https://raw.githubusercontent.com/exorde-labs/TestnetProtocol/main/NetworkConfig.json
source: https://raw.github.com/exorde-labs/TestnetProtocol/main/
contracts: ContractsAddresses.json
ABI:
  EXDT: ABIs/EXDT/EXDT.json 
  EXD: ABIs/EXD/EXD.json
  data-spotting: ABIs/DataSpotting.sol/DataSpotting.json
  reputation: ABIs/daostack/controller/daostack/controller/Reputation.sol/Reputation.json
  reward-manager: ABIs/RewardsManager.sol/RewardsManager.json
  stacking-manager: ABIs/StakingManager.sol/StakingManager.json
  config-registry: ABIs/ConfigRegistry.sol/ConfigRegistry.json
  address-manager: ABIs/AddressManager.sol/AddressManager.json
EXDT:
  address: '0xcBc357F3077989B4636E93a8Ce193E05cd8cc56E'
  private_key: 'deaddeaddeaddead5fb92d83ed54c0ea1eb74e72a84ef980d42953caaa6ddead'
  faucet: 2139927552
  faucet_base: 'deaddeaddeaddead5fb92d83ed54c0ea1eb74e72a84ef980d42953caaa6d'
keywords: https://raw.githubusercontent.com/exorde-labs/TestnetProtocol/main/targets/keywords.txt
